lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(JWT_TOKEN_TTL)%'
    token_extractors:
        cookie:
            enabled: true
            name: auth_token
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        query_parameter:
            enabled: false
    set_cookies:
        BEARER:
            path: /
            samesite: lax
            secure: '%env(SSL_ONLY)%'
            lifetime: '%env(JWT_TOKEN_TTL)%'
            httpOnly: true
