nelmio_api_doc:   
    documentation:
        # doc header title
        info:
            title: 'Engal API'
            description: Engal REST-API documentation
            version: '%env(APP_VERSION)%'

        # doc schemes components
        components:
            securitySchemes:
                DocSecurity:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT

        # security config
        security:
            - DocSecurity: []
            - api_key: []
            - basic: []
            - jwt:
                type: apiKey
                name: Authorization
                in: header
                description: JWT token

        # static docs
        paths:
            # JWT login endpoint
            /api/login:
                post:
                    tags: ['Auth']
                    summary: User login action.
                    description: User login JWT provider return JWT token
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                            default: test
                                        password:
                                            type: string
                                            default: test
                    responses:
                        200: 
                            description: Successful login (return token)
                        401: 
                            description: Invalid credentials
                        400: 
                            description: Bad request body data
