nelmio_cors:
    defaults:
        allow_origin: ['%env(resolve:ALLOWED_ORIGINS)%']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Accept', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'HEAD']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: true
        forced_allow_origin_value: null
