name: PHPStan

on:
  push:
    branches:
      - main
      - dev

jobs:
  phpstan:
    name: PHPStan analyse
    runs-on: ubuntu-latest
    steps:
    # checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # set up PHP environment
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.5

    # install project dependencies
    - name: Install dependencies
      run: composer install
      working-directory: ./backend

    # run PHPStan analysis
    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse --configuration phpstan.neon
      working-directory: ./backend
